---

# Specific install tasks for Debian family

- name: 'INSTALL | APT | Install system dependencies'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ redis_apt_cache_valid_time }}"
  with_items: "{{ redis_system_dependencies }}"


- name: 'INSTALL | APT | Manage repository key'
  apt_key:
    keyserver: "{{ redis_repository_keyserver }}"
    id: "{{ redis_repository_key_id }}"
  when: 'redis_manage_additional_repository'


- name: 'INSTALL | APT | Configure additional repositories'
  apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ item.codename | default(omit) }}"
    filename: "{{ item.filename | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ redis_repositories }}"
  when: 'redis_manage_additional_repository'


- name: 'INSTALL | APT | Install Redis server packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ redis_apt_cache_valid_time }}"
  notify: 'HANDLER | Restart Redis server'
  with_items: "{{ redis_server_packages }}"
  when: 'redis_manage_redis_server'


- name: 'INSTALL | APT | Install Redis Sentinel packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ redis_apt_cache_valid_time }}"
  notify: 'HANDLER | Restart Redis Sentinel'
  with_items: "{{ redis_sentinel_packages }}"
  when: 'redis_manage_redis_sentinel'
