---

# Main tasks file for redis role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::redis'
    - 'role::redis::init'


- name: 'INSTALL | Manage distribution specific installation tasks'
  become: True
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  tags:
    - 'role::redis'
    - 'role::redis::install'


- name: 'CONFIG | Manage configuration'
  become: True
  include: "{{ role_path }}/tasks/manage_configuration.yml"
  tags:
    - 'role::redis'
    - 'role::redis::config'


- name: 'SERVICE | Manage Redis services'
  become: True
  include: "{{ role_path }}/tasks/manage_services.yml"
  tags:
    - 'role::redis'
    - 'role::redis::config'
    - 'role::redis::install'
