---

# Main tasks file for redis role

- name: 'INIT | Manage variables to use for our target'
  include_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::redis'
    - 'role::redis::init'


- name: 'INSTALL | Manage system settings to increase Redis performances'
  become: True
  include_tasks: "{{ role_path }}/tasks/optimize_system.yml"
  when: 'redis_manage_system_optimization'
  tags:
    - 'role::redis'
    - 'role::redis::install'


- name: 'INSTALL | Manage distribution specific installation tasks'
  become: True
  include_tasks: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  tags:
    - 'role::redis'
    - 'role::redis::install'


- name: 'CONFIG | Manage configuration'
  become: True
  include_tasks: "{{ role_path }}/tasks/manage_configuration.yml"
  tags:
    - 'role::redis'
    - 'role::redis::config'
