---

# Main tasks file for redis role

- name: 'Load distribution variables'
  include_vars: "{{ role_path }}/vars/{{ ansible_distribution | lower }}.yml"
  tags:
    - 'redis'
    - 'install'


- name: 'Manage distribution specific installation tasks'
  include: "{{ role_path }}/tasks/install_{{ ansible_distribution|lower }}.yml"
  tags:
    - 'redis'
    - 'install'


- name: 'Install packages'
  become: True
  package:
    name: "{{ item }}"
  notify: 'restart_redis_server'
  with_items: "{{ redis_packages }}"
  tags:
    - 'redis'
    - 'install'


- name: 'Manage configuration'
  include: "{{ role_path }}/tasks/manage_configuration.yml"
  tags:
    - 'redis'
    - 'config'


- name: 'Enable redis server service'
  become: True
  service:
    name: "{{ redis_server_service_name }}"
    state: "{{ redis_server_service_state }}"
    enabled: "{{ redis_server_service_enabled }}"
  tags:
    - 'redis'
    - 'install'
