---

# Handlers main file for redis role

- name: 'HANDLER | Restart Redis server'
  become: True
  service:
    name: "{{ redis_server_service_name }}"
    state: 'restarted'
  tags:
    - 'role::redis'
    - 'role::redis::config'
    - 'role::redis::install'


- name: 'HANDLER | Restart Redis Sentinel'
  become: True
  service:
    name: "{{ redis_sentinel_service_name }}"
    state: 'restarted'
  tags:
    - 'role::redis'
    - 'role::redis::config'
    - 'role::redis::install'
